import type { Category, Product } from "@/lib/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Corporate Awards",
    slug: "corporate-awards",
    description: "Recognise outstanding business achievement",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-2",
    name: "Sports Trophies",
    slug: "sports-trophies",
    description: "Celebrate sporting excellence",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-3",
    name: "Crystal Awards",
    slug: "crystal-awards",
    description: "Premium crystal recognition pieces",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-4",
    name: "Glass Awards",
    slug: "glass-awards",
    description: "Elegant glass trophies and plaques",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-5",
    name: "Academic Awards",
    slug: "academic-awards",
    description: "Honour educational achievement",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-6",
    name: "Custom Medals",
    slug: "custom-medals",
    description: "Fully bespoke medals for any occasion",
    image_url: null,
    created_at: "2024-01-01T00:00:00Z",
  },
];

const corporateCategory = MOCK_CATEGORIES[0];
const sportsCategory = MOCK_CATEGORIES[1];
const crystalCategory = MOCK_CATEGORIES[2];
const glassCategory = MOCK_CATEGORIES[3];
const academicCategory = MOCK_CATEGORIES[4];
const medalCategory = MOCK_CATEGORIES[5];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Executive Crystal Star Award",
    slug: "executive-crystal-star-award",
    description:
      "A stunning hand-crafted crystal star award, perfect for recognising top-tier executive achievement. Each piece is individually polished and can be fully personalised with engraving.",
    short_description: "Hand-crafted crystal star for executive recognition",
    category_id: "cat-3",
    category: crystalCategory,
    base_price: 89.99,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["crystal"],
    sizes: ["medium", "large"],
    is_customisable: true,
    is_featured: true,
    is_active: true,
    stock_quantity: 50,
    weight_grams: 800,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-2",
    name: "Gold Champion Trophy",
    slug: "gold-champion-trophy",
    description:
      "A classic gold-plated champion's trophy with a marble base. Ideal for sports competitions, tournaments, and team celebrations. Available in three sizes.",
    short_description: "Classic gold-plated trophy on marble base",
    category_id: "cat-2",
    category: sportsCategory,
    base_price: 54.99,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["metal"],
    sizes: ["small", "medium", "large"],
    is_customisable: true,
    is_featured: true,
    is_active: true,
    stock_quantity: 100,
    weight_grams: 1200,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "prod-3",
    name: "Premium Glass Plaque",
    slug: "premium-glass-plaque",
    description:
      "An elegant bevelled glass plaque with deep-etched engraving. Perfect for long-service awards, employee of the month, and board recognition programmes.",
    short_description: "Bevelled glass plaque with deep-etched engraving",
    category_id: "cat-4",
    category: glassCategory,
    base_price: 42.50,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["glass"],
    sizes: ["small", "medium"],
    is_customisable: true,
    is_featured: true,
    is_active: true,
    stock_quantity: 75,
    weight_grams: 600,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
  },
  {
    id: "prod-4",
    name: "Corporate Achievement Shield",
    slug: "corporate-achievement-shield",
    description:
      "A prestigious wooden shield award with a brass plate, ideal for corporate recognition ceremonies and annual awards dinners. Comes in a presentation box.",
    short_description: "Wooden shield with brass plate in presentation box",
    category_id: "cat-1",
    category: corporateCategory,
    base_price: 67.00,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["wood", "metal"],
    sizes: ["medium", "large"],
    is_customisable: true,
    is_featured: true,
    is_active: true,
    stock_quantity: 40,
    weight_grams: 900,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-04T00:00:00Z",
    updated_at: "2024-01-04T00:00:00Z",
  },
  {
    id: "prod-5",
    name: "Academic Excellence Medal",
    slug: "academic-excellence-medal",
    description:
      "A solid brass academic medal with ribbon, designed for graduation ceremonies and academic competitions. Custom ribbon colours available.",
    short_description: "Solid brass medal with custom ribbon",
    category_id: "cat-5",
    category: academicCategory,
    base_price: 18.99,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["metal"],
    sizes: ["small"],
    is_customisable: true,
    is_featured: false,
    is_active: true,
    stock_quantity: 200,
    weight_grams: 150,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "prod-6",
    name: "Bespoke Engraved Medal",
    slug: "bespoke-engraved-medal",
    description:
      "Fully bespoke die-cast medal with your own design. Choose shape, finish, and ribbon colour. Minimum order 10 units. Perfect for marathons, charity events, and competitions.",
    short_description: "Fully custom die-cast medal, minimum 10 units",
    category_id: "cat-6",
    category: medalCategory,
    base_price: 12.50,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["metal"],
    sizes: ["small", "medium"],
    is_customisable: true,
    is_featured: false,
    is_active: true,
    stock_quantity: 500,
    weight_grams: 120,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-06T00:00:00Z",
    updated_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "prod-7",
    name: "Crystal Cube Paperweight Award",
    slug: "crystal-cube-paperweight-award",
    description:
      "A weighty optical crystal cube with full-colour internal photo engraving. A truly unique keepsake award that sits beautifully on any desk.",
    short_description: "Optical crystal cube with photo engraving",
    category_id: "cat-3",
    category: crystalCategory,
    base_price: 74.99,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["crystal"],
    sizes: ["small", "medium"],
    is_customisable: true,
    is_featured: false,
    is_active: true,
    stock_quantity: 30,
    weight_grams: 1100,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-07T00:00:00Z",
    updated_at: "2024-01-07T00:00:00Z",
  },
  {
    id: "prod-8",
    name: "Acrylic Recognition Award",
    slug: "acrylic-recognition-award",
    description:
      "A modern full-colour printed acrylic award, vibrant and lightweight. Great for employee recognition, community awards, and events on a budget.",
    short_description: "Full-colour printed modern acrylic award",
    category_id: "cat-1",
    category: corporateCategory,
    base_price: 29.99,
    images: [
      "https://picsum.photos/id/175/600/600",
    ],
    materials: ["acrylic"],
    sizes: ["small", "medium", "large"],
    is_customisable: true,
    is_featured: false,
    is_active: true,
    stock_quantity: 120,
    weight_grams: 300,
    meta_title: null,
    meta_description: null,
    created_at: "2024-01-08T00:00:00Z",
    updated_at: "2024-01-08T00:00:00Z",
  },
];

/** Returns the 4 featured mock products */
export const MOCK_FEATURED_PRODUCTS = MOCK_PRODUCTS.filter(
  (p) => p.is_featured
);
